name: Count Ads & Phones

on:
  workflow_dispatch:
    inputs:
      date:
        description: "Date (YYYY-MM-DD)"
        required: true
        default: "2026-07-20"

jobs:
  count:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          CF_R2_ACCESS_KEY_ID: ${{ secrets.CF_R2_ACCESS_KEY_ID }}
          CF_R2_SECRET_ACCESS_KEY: ${{ secrets.CF_R2_SECRET_ACCESS_KEY }}
          CF_R2_ENDPOINT_URL: ${{ secrets.CF_R2_ENDPOINT_URL }}
          CF_R2_BUCKET_NAME: ${{ secrets.CF_R2_BUCKET_NAME }}
        run: |
          python main.py --date "${{ github.event.inputs.date }}"